const SUPABASE_URL='https://imkbmemvoqbbedbljueu.supabase.co';
const SUPABASE_PUBLISHABLE_KEY='sb_publishable_Dosi6rJmV4SaGzLEClAYUA_1L2CdDfE';
const {createClient}=window.supabase; const sb=createClient(SUPABASE_URL,SUPABASE_PUBLISHABLE_KEY); const BUCKET='resources';
const TRASH='.trash'; const STORAGE_QUOTA=10*1024**3;
let user=null,currentPath='',pendingAction=null,allItems=[],mode='normal',previewName='',shareUrl='';
const $=id=>document.getElementById(id); const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const cleanName=v=>String(v||'').trim().replace(/[\\/]/g,'-').replace(/\.{2,}/g,'.').slice(0,160); const join=(a,b)=>[a,b].filter(Boolean).join('/');
const storagePath=()=>join(user.id,currentPath); const trashPath=()=>join(user.id,TRASH); const keyPrefix=()=>`izvault-resource-${user.id}`;
const toast=m=>{ $('toast').textContent=m; $('toast').classList.remove('hidden'); clearTimeout(window.__toast); window.__toast=setTimeout(()=>$('toast').classList.add('hidden'),3200); };
const openModal=id=>$(id).classList.add('show'); const closeModal=id=>$(id).classList.remove('show');
function bytes(n){if(!n)return'0 B';const u=['B','KB','MB','GB','TB'],i=Math.min(Math.floor(Math.log(n)/Math.log(1024)),4);return`${(n/1024**i).toFixed(i?1:0)} ${u[i]}`}
function ext(n){return n.split('.').pop().toLowerCase()}
function isImage(n){return['jpg','jpeg','png','gif','webp','svg'].includes(ext(n))} function isPdf(n){return ext(n)==='pdf'}
function category(n){const e=ext(n);if(isImage(n))return'image';if(isPdf(n))return'pdf';if(['doc','docx','txt','rtf','odt'].includes(e))return'document';if(['mp4','mov','webm','mkv','avi'].includes(e))return'video';if(['zip','rar','7z','tar','gz'].includes(e))return'archive';return'other'}
function icon(n,f=false){if(f)return'fa-folder';if(isImage(n))return'fa-image';if(isPdf(n))return'fa-file-pdf';if(category(n)==='document')return'fa-file-lines';if(['ppt','pptx'].includes(ext(n)))return'fa-file-powerpoint';if(['xls','xlsx','csv'].includes(ext(n)))return'fa-file-excel';if(category(n)==='archive')return'fa-file-zipper';if(['psd','ai','fig'].includes(ext(n)))return'fa-palette';if(category(n)==='video')return'fa-file-video';return'fa-file'}
function stars(){try{return JSON.parse(localStorage.getItem(`${keyPrefix()}-stars`)||'[]')}catch{return[]}} function setStars(a){localStorage.setItem(`${keyPrefix()}-stars`,JSON.stringify(a))}
function recents(){try{return JSON.parse(localStorage.getItem(`${keyPrefix()}-recent`)||'[]')}catch{return[]}} function addRecent(path){let a=recents().filter(x=>x!==path);a.unshift(path);localStorage.setItem(`${keyPrefix()}-recent`,JSON.stringify(a.slice(0,30)))}
async function init(){const {data:{session}}=await sb.auth.getSession();user=session?.user||null;if(!user){toast('Please log in to access cloud Resources.');setTimeout(()=>location.href='index.html',900);return}$('accountName').textContent=user.user_metadata?.username||user.email?.split('@')[0]||'User';bind();await load()}
function bind(){$('uploadBtn').onclick=()=>$('fileInput').click();$('fileInput').onchange=async e=>{if(e.target.files.length)await uploadFiles([...e.target.files]);e.target.value=''};$('newFolderBtn').onclick=()=>{$('folderName').value='';openModal('folderModal');setTimeout(()=>$('folderName').focus(),50)};$('createFolder').onclick=createFolder;$('refreshBtn').onclick=load;$('search').oninput=render;$('typeFilter').onchange=render;$('sortSelect').onchange=render;$('starredBtn').onclick=()=>setMode(mode==='starred'?'normal':'starred');$('recentBtn').onclick=()=>setMode(mode==='recent'?'normal':'recent');$('trashBtn').onclick=()=>setMode(mode==='trash'?'normal':'trash');$('gridBtn').onclick=()=>document.body.classList.remove('listmode');$('listBtn').onclick=()=>document.body.classList.add('listmode');document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>closeModal(b.dataset.close));$('renameSave').onclick=renameItem;$('deleteConfirm').onclick=deleteItem;$('copyShare').onclick=async()=>{try{await navigator.clipboard.writeText(shareUrl);toast('Share link copied.')}catch{toast('Could not copy automatically.')}};$('previewDownload').onclick=()=>previewName&&downloadFile(previewName);const dz=$('dropzone');dz.ondragover=e=>{e.preventDefault();dz.classList.add('drag')};dz.ondragleave=()=>dz.classList.remove('drag');dz.ondrop=async e=>{e.preventDefault();dz.classList.remove('drag');const files=[...e.dataTransfer.files];if(files.length)await uploadFiles(files)}}
async function listObjects(prefix=''){const {data,error}=await sb.storage.from(BUCKET).list(prefix,{limit:1000,sortBy:{column:'name',order:'asc'}});if(error)throw error;return data||[]}
async function recursiveFiles(prefix){const data=await listObjects(prefix);let out=[];for(const x of data){const p=join(prefix,x.name);const folder=x.id===null||x.metadata===null;if(x.name==='.folder')continue;if(folder)out.push(...await recursiveFiles(p));else out.push({path:p,name:x.name,size:x.metadata?.size||0,updated:x.updated_at||x.created_at||null});}return out}
async function calculateStorage(){try{const f=await recursiveFiles(user.id);return f.reduce((s,x)=>s+(x.size||0),0)}catch{return 0}}
async function load(){try{const prefix=mode==='trash'?trashPath():storagePath();allItems=await listObjects(prefix);render();const used=await calculateStorage();$('storageUsed').textContent=bytes(used);$('storageLabel').textContent=`${bytes(used)} used of 10 GB`;$('storageBar').style.width=`${Math.min(100,used/STORAGE_QUOTA*100)}%`}catch(e){console.error(e);toast(`Could not load Resources: ${e.message||'Storage is not configured.'}`);$('grid').innerHTML='<div class="empty"><i class="fa-solid fa-cloud"></i><br><br>Cloud storage is not ready yet.<br>Run the Resources storage setup in Supabase SQL Editor.</div>'}}
function setMode(m){mode=m;currentPath='';$('pageTitle').textContent=m==='trash'?'Trash':m==='starred'?'Starred':m==='recent'?'Recent Files':'My Files';$('pageSubtitle').textContent=m==='trash'?'Deleted items are kept here until permanently removed.':m==='starred'?'Your important files and folders.':m==='recent'?'Files you opened or uploaded recently.':'Organise your work, projects and downloads in the cloud.';load()}
function render(){const q=$('search').value.trim().toLowerCase(),filter=$('typeFilter').value,sort=$('sortSelect').value,star=stars(),recent=recents();let items=allItems.filter(x=>x.name!=='.folder');const folders=items.filter(x=>x.id===null||x.metadata===null),files=items.filter(x=>x.id!==null&&x.metadata!==null);items=items.filter(x=>{const f=folders.includes(x),c=f?'folder':category(x.name);if(filter!=='all'&&c!==filter)return false;if(q&&!x.name.toLowerCase().includes(q))return false;if(mode==='starred'&&!star.includes(join(storagePath(),x.name)))return false;if(mode==='recent'&&!recent.includes(join(storagePath(),x.name)))return false;return true});items.sort((a,b)=>{if(sort==='newest')return String(b.updated_at||b.created_at||'').localeCompare(String(a.updated_at||a.created_at||''));if(sort==='oldest')return String(a.updated_at||a.created_at||'').localeCompare(String(b.updated_at||b.created_at||''));if(sort==='size')return (b.metadata?.size||0)-(a.metadata?.size||0);if(sort==='type')return category(a.name).localeCompare(category(b.name));return a.name.localeCompare(b.name)});$('fileCount').textContent=mode==='trash'?'—':files.length;$('folderCount').textContent=mode==='trash'?'—':folders.length;$('currentFolder').textContent=mode==='trash'?'Trash':currentPath?currentPath.split('/').pop():'Root';renderPath();if(!items.length){$('grid').innerHTML=`<div class="empty"><i class="fa-solid ${mode==='trash'?'fa-trash':'fa-folder-open'}" style="font-size:30px"></i><br><br>${mode==='trash'?'Trash is empty.':'No files or folders here yet.'}<br><small>${mode==='trash'?'Deleted items will appear here.':'Upload a file or create a folder to get started.'}</small></div>`;return}$('grid').innerHTML=items.map(x=>card(x,folders.includes(x),star,recent)).join('')}
function card(x,f,star,recent){const n=x.name,path=join(mode==='trash'?trashPath():storagePath(),n),isStar=star.includes(path),isRecent=recent.includes(path),m=f?'Folder':`${category(n).toUpperCase()} • ${bytes(x.metadata?.size||0)}`;let primary=f?`<button class="mini" onclick='openFolder(${JSON.stringify(n)})'>Open</button>`:((isImage(n)||isPdf(n))?`<button class="mini" onclick='previewFile(${JSON.stringify(n)})'>View</button>`:`<button class="mini" onclick='downloadFile(${JSON.stringify(n)})'>Download</button>`);if(mode==='trash'){return`<article class="item"><div><div class="itemtop"><div class="icon"><i class="fa-solid ${icon(n,f)}"></i></div></div><div class="name">${esc(n)}</div><div class="meta">${m}</div></div><div class="itemactions"><button class="mini" onclick='restoreItem(${JSON.stringify(n)},${f})'>Restore</button><button class="mini danger" onclick='startPermanentDelete(${JSON.stringify(n)},${f})'>Delete Permanently</button></div></article>`}return`<article class="item"><div><div class="itemtop"><div class="icon"><i class="fa-solid ${icon(n,f)}"></i></div><button class="star ${isStar?'on':''}" title="${isStar?'Unstar':'Star'}" onclick='toggleStar(${JSON.stringify(path)})'><i class="fa-${isStar?'solid':'regular'} fa-star"></i></button></div><div class="name">${esc(n)}</div><div class="meta">${m}${isRecent?' • Recent':''}</div></div><div class="itemactions">${primary}<button class="mini" onclick='startRename(${JSON.stringify(n)},${f})'>Rename</button><button class="mini" onclick='shareItem(${JSON.stringify(n)},${f})'>Share</button><button class="mini danger" onclick='startDelete(${JSON.stringify(n)},${f})'>Trash</button>${f?`<button class="mini" onclick='downloadZip(${JSON.stringify(n)})'>ZIP</button>`:''}</div></article>`}
function renderPath(){if(mode!=='normal'){ $('path').innerHTML=`<button onclick="setMode('normal')"><i class="fa-solid fa-house"></i> My Files</button><span>/</span><span>${esc(mode[0].toUpperCase()+mode.slice(1))}</span>`;return}const parts=currentPath?currentPath.split('/'):[];let h='<button onclick="goRoot()"><i class="fa-solid fa-house"></i> Root</button>',b='';parts.forEach(p=>{b=join(b,p);h+=`<span>/</span><button onclick='goPath(${JSON.stringify(b)})'>${esc(p)}</button>`});$('path').innerHTML=h}
window.goRoot=()=>{currentPath='';load()};window.goPath=p=>{currentPath=p;load()};window.openFolder=n=>{if(mode!=='normal')return;currentPath=join(currentPath,n);load()};
async function uploadFiles(files){openModal('uploadModal');let ok=0;for(let i=0;i<files.length;i++){const file=files[i],n=cleanName(file.name);if(!n)continue;$('uploadStatus').textContent=`Uploading ${i+1} of ${files.length}: ${n}`;$('uploadProgress').textContent=`${Math.round(i/files.length*100)}%`;const p=join(storagePath(),n);const {error}=await sb.storage.from(BUCKET).upload(p,file,{upsert:false,contentType:file.type||'application/octet-stream'});if(error)toast(`${n}: ${error.message}`);else ok++}$('uploadProgress').textContent='100%';$('uploadStatus').textContent=`${ok} file${ok!==1?'s':''} uploaded successfully.`;await load();setTimeout(()=>closeModal('uploadModal'),700)}
async function createFolder(){const n=cleanName($('folderName').value);if(!n)return toast('Enter a folder name.');const p=join(storagePath(),join(n,'.folder'));const {error}=await sb.storage.from(BUCKET).upload(p,new Blob(['IzVault folder'],{type:'text/plain'}),{upsert:false,contentType:'text/plain'});if(error)return toast(`Could not create folder: ${error.message}`);closeModal('folderModal');toast('Folder created successfully.');await load()}
async function signedAt(path,seconds=3600){const {data,error}=await sb.storage.from(BUCKET).createSignedUrl(path,seconds);if(error)throw error;return data.signedUrl}
async function signed(name){return signedAt(join(storagePath(),name),3600)}
async function downloadFile(name){try{const p=join(mode==='trash'?trashPath():storagePath(),name),u=await signedAt(p,3600);addRecent(join(storagePath(),name));const a=document.createElement('a');a.href=u;a.download=name;a.target='_blank';a.rel='noopener';a.click();toast('Download started.')}catch(e){toast(`Download failed: ${e.message}`)}}window.downloadFile=downloadFile;
async function previewFile(name){try{const u=await signed(name);previewName=name;$('previewBody').innerHTML=isImage(name)?`<img src="${u}" alt="${esc(name)}"><p>${esc(name)}</p>`:`<iframe src="${u}" title="${esc(name)}"></iframe>`;addRecent(join(storagePath(),name));openModal('previewModal')}catch(e){toast(`Preview failed: ${e.message}`)}}window.previewFile=previewFile;
window.toggleStar=path=>{let a=stars();a=a.includes(path)?a.filter(x=>x!==path):[...a,path];setStars(a);render();toast(a.includes(path)?'Added to Starred.':'Removed from Starred.')};
window.startRename=(name,folder)=>{pendingAction={name,folder};$('renameName').value=name;openModal('renameModal');setTimeout(()=>$('renameName').focus(),50)};
async function renameItem(){const old=pendingAction?.name,next=cleanName($('renameName').value),folder=pendingAction?.folder;if(!old||!next)return toast('Enter a valid name.');if(old===next){closeModal('renameModal');return}const base=storagePath(),from=join(base,old),to=join(base,next);try{if(folder){await moveTree(from,to)}else{const {error}=await sb.storage.from(BUCKET).move(from,to);if(error)throw error}closeModal('renameModal');toast('Renamed successfully.');await load()}catch(e){toast(`Rename failed: ${e.message}`)}}
async function moveTree(from,to){const data=await listObjects(from);for(const x of data){const a=join(from,x.name),b=join(to,x.name),folder=x.id===null||x.metadata===null;if(folder){await moveTree(a,b)}else{const {error}=await sb.storage.from(BUCKET).move(a,b);if(error)throw error}}const marker=data.some(x=>x.name==='.folder');if(marker){const {error}=await sb.storage.from(BUCKET).move(join(from,'.folder'),join(to,'.folder'));if(error)throw error}}
window.startDelete=(name,folder)=>{pendingAction={name,folder,permanent:false};$('deleteTitle').textContent='Move to Trash?';$('deleteText').textContent=`“${name}” will be moved to Trash and can be restored later.`;$('deleteConfirm').textContent='Move to Trash';openModal('deleteModal')};
window.startPermanentDelete=(name,folder)=>{pendingAction={name,folder,permanent:true};$('deleteTitle').textContent='Delete permanently?';$('deleteText').textContent=`“${name}” will be permanently deleted. This cannot be undone.`;$('deleteConfirm').textContent='Delete Permanently';openModal('deleteModal')};
async function collectFiles(prefix){const data=await listObjects(prefix);let paths=[];for(const x of data){const p=join(prefix,x.name);if(x.name==='.folder'){paths.push(p);continue}const folder=x.id===null||x.metadata===null;if(folder)paths.push(...await collectFiles(p));else paths.push(p)}return paths}
async function deleteItem(){const {name,folder,permanent}=pendingAction||{};if(!name)return;const base=permanent?trashPath():storagePath(),p=join(base,name);try{if(permanent){const paths=folder?await collectFiles(p):[p];if(paths.length){const {error}=await sb.storage.from(BUCKET).remove(paths);if(error)throw error}}else{const dest=join(trashPath(),`${Date.now()}-${cleanName(name)}`);if(folder)await moveTree(p,dest);else{const {error}=await sb.storage.from(BUCKET).move(p,dest);if(error)throw error}}closeModal('deleteModal');toast(permanent?'Deleted permanently.':'Moved to Trash.');await load()}catch(e){toast(`Delete failed: ${e.message}`)}}
window.restoreItem=async(name,folder)=>{try{const p=join(trashPath(),name),dest=join(storagePath(),name.replace(/^\d+-/,''));if(folder)await moveTree(p,dest);else{const {error}=await sb.storage.from(BUCKET).move(p,dest);if(error)throw error}toast('Restored successfully.');await load()}catch(e){toast(`Restore failed: ${e.message}`)}};
async function shareItem(name,folder){if(folder)return toast('Sharing folders is not supported yet. Share individual files instead.');try{shareUrl=await signedAt(join(storagePath(),name),86400);$('shareUrl').textContent=shareUrl;openModal('shareModal');addRecent(join(storagePath(),name))}catch(e){toast(`Could not create share link: ${e.message}`)}}window.shareItem=shareItem;
async function downloadZip(folderName){try{if(!window.JSZip)throw new Error('ZIP library is not ready.');const files=await recursiveFiles(join(storagePath(),folderName));if(!files.length)return toast('This folder is empty.');openModal('uploadModal');$('uploadStatus').textContent=`Preparing ZIP: ${folderName}`;$('uploadProgress').textContent=`0 / ${files.length}`;const zip=new JSZip();for(let i=0;i<files.length;i++){const u=await signedAt(files[i].path,600),r=await fetch(u),blob=await r.blob();zip.file(files[i].path.slice(join(storagePath(),folderName).length+1),blob);$('uploadProgress').textContent=`${i+1} / ${files.length}`}const blob=await zip.generateAsync({type:'blob',compression:'DEFLATE'});const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=`${folderName}.zip`;a.click();URL.revokeObjectURL(u);closeModal('uploadModal');toast('ZIP download ready.')}catch(e){closeModal('uploadModal');toast(`ZIP failed: ${e.message}`)}}window.downloadZip=downloadZip;
init();